### ISSUE TITLE
项目与开发管理：仅有项目集管理，缺少项目管理

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#11]

**Comment by aintover** [comment]
项目管理部分需要增加风险管理

**Comment by ijyun** [comment]
> 项目管理部分需要增加风险管理

项目风险管理属于传统PMP项目管理的范围，在DevOps模式下，项目风险管理依然存在，但是项目主要是作为后续流程的起点或基础，关注点依然是从需求到线上服务的交付。

结论是：不建议增加

**Comment by ijyun** [comment]
请负责项目管理的 @kaverjody 老师也看一下

**Comment by ijyun** [comment]
新版已经包含项目管理
