### ISSUE TITLE
是否考虑在图谱中加入看板管理相关的内容？

### ISSUE THREAD

**Issue by patrickiochan** [docmm/09-devops-system-tool#117]
电子看板在端到端打通方面非常重要，同时也是数字化管理落地的重要手段。特别是对于规模比较大的组织来说。

**Comment by yaojianmang** [comment]
计划与任务管理已经包括任务看板管理，而且电子看板是一种表现形式，不是一个对象。
个人建议图谱中不增加电子看板。

**Comment by kaverjody** [comment]
“看板”这个中文词确实很容易引起误解，至少有两个语义，一个是Trello那种管理任务性质的板子，一个其实是说仪表盘，显示一些统计数据的板子。

**Comment by ijyun** [comment]
请 @yaojianmang @kaverjody @bearrui 三位老师一起关注一下，主要是计划管理这块，我狭义的理解Kanban还是属于计划管理的一种形式，关注价值流动和工作量。即需求和任务在时间维度的展现（包含负责的人员信息）

**Comment by kaverjody** [comment]
目前的版本已修改，“支持工作项的可视化管理”、“支持可视化视图模板”可以涵盖看板板的内容，“支持项目流程模板自定义”可涵盖看板方法。
