### ISSUE TITLE
项目集管理：基本功能__设置里程碑，分配负责人。这一条的疑问在于，项目集有里程碑吗？

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#20]

**Comment by eLevenD11** [comment]
在实践中，嵌套多层的项目集也会需要里程碑，若下钻到项目才能看到里程碑，项目集的管理者较难把控项目集进展。可更改为高级功能，请各位专家评定。

**Comment by kaverjody** [comment]
由于这里涉及到项目、项目集这两个概念的定义和关系，参考3.1和3.2部分对两个术语的定义，我认同项目集也是应该有里程碑的。虽然这样一来项目集里程碑和项目里程碑是啥关系估计还得探讨，但我觉得延续我们在第3章术语里面的定义的化，应该要认可项目集存在里程碑。

3.1　项目 project

需要协同工作的一组任务，其目的在于开发和（或）维护一个具体的产品。产品可以包括硬件、软件或其他成分，一般项目有自己的经费、成本核算和交付进度。【GB/T11457-2006：2.954】

3.2　项目集 program

PMI将项目集定义为经过协调管理以获取单独管理所无法取得的收益的一组项目、子项目集和项目集活动。

**Comment by dongyue** [comment]
好，我close了。
