### ISSUE TITLE
项目集管理：基本功能__录入需求、任务。专家建议调整为“录入或关联需求与任务”。

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#21]

**Comment by eLevenD11** [comment]
赞同依专家建议调整

**Comment by kaverjody** [comment]
建议按照被操作对象区分开来，需求、任务分开来写；然后操作可以汇集在一起。

如果是“录入或关联需求与任务”，可以考虑：
- 支持录入和修改需求
- 支持录入和修改任务
- 支持关联需求与任务

如上只是建议，需要看看写作者如下两行的原意是啥
——录入需求、任务【建议调整为录入或关联需求与任务】
——录入或关联需求任务
