### ISSUE TITLE
项目集管理：基本功能__记录跟踪项目集风险。请解释如何进行风险管理？

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#22]

**Comment by eLevenD11** [comment]
发现项目集有风险，将风险记录下来，指派给相关人，标记严重程度，记录解决方案等

**Comment by kaverjody** [comment]
建议按照 @eLevenD11 提到的几个动作分别写清楚，这些就是功能，例如：
- 录入风险
- 标记严重程度
- 指派处理人
- 录入应对措施
- 录入和修改状态
- 等等

**Comment by dongyue** [comment]
少量文字改动，改为“记录和跟踪项目集风险：录入风险、标记严重程度、指派处理人、录入应对措施等，并用状态标记风险是否已解决。”。考虑到这些内容都是围绕着记录和跟踪项目集风险，如果分列为多条，与其他内容并列，在逻辑上不太和谐。
