### ISSUE TITLE
云IDE：专家建议将全文的列举的句式统一为——“包含但不限于xxx”；提前定义需要用到的术语，比如对xx服务提前进行术语定义；“服务”替换成“系统和工具”；基础功能与高级功能的划分问题

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#29]

**Comment by ijyun** [comment]
@ovmarschen @juweigang @dongyue @niuxiaoling-666 大家都可以关注一下，包含但不限于这样的表述方式，是指必须包括枚举出来的，但是还有其他没有枚举到的内容。

**Comment by kaverjody** [comment]
1，句式根据之前几次会议的意见，去掉容易引发误解的“包含”，目前保留了“不限于”；
2，提前定义术语，由于内容已经进行了多次修改，请根据最新版本确认，如仍有问题，请提交issue；
3，服务目前未替换为系统和工具，前几次会议现场其他专家并未提出异议，暂时保留，如有异议，请新提交issue；
4，基础与高级功能划分：请根据最新版本确认，如仍有问题，请新提交issue；
