### ISSUE TITLE
持续交付与持续集成：应增加持续交付和持续集成的概念描述

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#38]

**Comment by danielfbm** [comment]
持续集成描述已添加。请见 https://github.com/docmm/09-devops-system-tool/pull/104

**Comment by ijyun** [comment]
@danielfbm @brandonliuxiong 以两位的意见为准

**Comment by dongyue** [comment]
补充了持续交付定义，见 pull/182
