### ISSUE TITLE
持续集成：专家建议合并到构建管理；CI/CD等价，不是包含关系；流水线中存在构建环节

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#40]

**Comment by danielfbm** [comment]
@dongyue @niuxiaoling-666 @kaverjody @ijyun 这个问题大家有什么建议么？要不我先发一个PR为proposal？

**Comment by danielfbm** [comment]
因为有些内容重叠了可以考虑把 #87 一起解决

**Comment by danielfbm** [comment]
@kaverjody 同意，其实11月30号的会议中讨论了这个issue，主要结论是构建的参考产品是 maven，ant等等，所以也满足不了CI的要求。从这个角度来说还是分开为好。如果其他专家没有意见要不先关闭此 issue?

**Comment by patrickiochan** [comment]
同意楼上两位的说法。按照老马和jez humble的说法，持续集成不是一件很容易的事情，大多数公司做的都是“假的”持续集成。而流水线主要是工具层面的东西，持续的用流水线，遵循相关的原则，相对容易达成持续集成或者持续交付的目标；但是不遵循相关的原则，通过流水线也能解决开发、编译、测试和不说过程中的一些效率问题。所以从这个角度来说，应该要分开来。

**Comment by kaverjody** [comment]
鉴于近两个月没有新的回复，关闭此Issue。
