### ISSUE TITLE
部署管理：这里的描述与上下文的功能型描述不一致，建议改为“支持xx功能”。

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#53]
生产环境的管理还是测试环境？此处是生产管理的，专家建议包含生产环境和测试环境。

**Comment by ramboyang11** [comment]
部署管理是DevOps持续交付中的一个重要环节，它借助自动化工具与统一规范，实现仓库版本到测试环境、生产环境的自动化部署，加速版本软件到线上运营的流转效率，提升开发、运维人员快速部署的能力。
