### ISSUE TITLE
发布管理：发布管理是指一个应用或多个集成应用程序从测试完成到生产环境用户可见的发布流程。定义混淆，如何和部署区分？

### ISSUE THREAD

**Issue by niuxiaoling-666** [docmm/09-devops-system-tool#60]

**Comment by kujing** [comment]
部署没有任何风险，可以是任何环境，而发布是将应用发布到生产环境

**Comment by kujing** [comment]
查了一些资料，总结下部署策略
部署策略：
		全量部署（覆盖）
		*滚动升级/发布
		*蓝绿部署/发布
		*金丝雀发布（灰度发布）A/B测试
		版本化部署

**Comment by kujing** [comment]
已明确和部署区分，发布管理是产品从测试完成到生产环境可见的一个过程。部署是所有环境的部署动作

**Comment by ijyun** [comment]
👍
